### ISSUE TITLE
Add support for getting process memory and cpu usage information

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-windows-process-tree#12]
- [x] Add option to get memory for each process https://github.com/Microsoft/vscode-windows-process-tree/pull/11
- [x] Add option to get CPU usage for each process https://github.com/Microsoft/vscode-windows-process-tree/pull/13
- [x] Add option to get command line arguments for each process https://github.com/Microsoft/vscode-windows-process-tree/pull/17

**Comment by weinand** [comment]
@RMacfarlane @Tyriar I would like to use these features but the npm module is not yet available, correct?
It would be great if you could publish this as soon as possible (so that I can use this in the March release of node-debug).

**Comment by Tyriar** [comment]
@weinand master should be on the new v0.2.0 :+1:
