### ISSUE TITLE
Increase commandLine length limit

### ISSUE THREAD

**Issue by RMacfarlane** [Microsoft/vscode-windows-process-tree#23]
The current limit, 512 characters, is rather low. See if there is a way to increase this limit

**Comment by Tyriar** [comment]
Maybe we can just up [it](https://github.com/Microsoft/vscode-windows-process-tree/blob/d6bbc511dd97728a2d7e58df5a12f057bcf64122/src/process.h#L24) to 4096? I don't think it's much of a hit if that's too high generally.

**Comment by RMacfarlane** [comment]
The default stack size seems to be 984kb (`node --v8-options | grep -A1 stack_size`), so to increase it that much, it needs to be run with a higher stack size. Do we do that in VS Code?

I tried changing `ProcessInfo process_info[1024]` to `ProcessInfo* process_info = new ProcessInfo[1024]` to allocate on the heap, deleting at the end of HandleOkCallback in the worker, but this causes the "should handle multiple calls gracefully" test to always fail with an access violation error.

One workaround would just be to flip the size of the process_info and commandLine arrays, so that we only read up to 512 processes and read up to 1024 chars of commandLine
